app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`home-piechart_brush` = brushselected, allowInputNoBinding_ = TRUE)
app$setInputs(`home-poland_map_brush` = brushselected, allowInputNoBinding_ = TRUE)
app$setInputs(`home-timeline_brush` = brushselected, allowInputNoBinding_ = TRUE)
app$setInputs(`Map-note_out-notesSel` = "ciao")
app$setInputs(uisidebar = "Map", allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`Map-map_groups` = c("Acrocephalus paludicola", "Propylea quatuordecimpunctata"), allowInputNoBinding_ = TRUE)
app$setInputs(`Map-map_bounds` = c(57.0885153278865, 28.6083984375, 46.2558468184803, 11.42578125), allowInputNoBinding_ = TRUE)
app$setInputs(`Map-map_center` = c(20.01708984375, 51.9984103823903), allowInputNoBinding_ = TRUE)
app$setInputs(`Map-sptime_brush` = brushselected, allowInputNoBinding_ = TRUE)
app$setInputs(`Map-vernacularInput` = "Common Crane")
app$setInputs(`Map-map_groups` = "Grus grus", allowInputNoBinding_ = TRUE)
app$setInputs(`Map-vernacularInput` = c("Common Crane", "Common Merganser"))
app$setInputs(`Map-map_groups` = c("Grus grus", "Mergus merganser"), allowInputNoBinding_ = TRUE)
app$setInputs(`Map-vernacularInput` = c("Common Crane", "Common Merganser", "Hooded Crow"))
app$setInputs(`Map-map_groups` = c("Grus grus", "Mergus merganser", "Corvus cornix"), allowInputNoBinding_ = TRUE)
app$snapshot()
